{
 "title": "Conduktor Console",
 "description": "Conduktor console monitoring",
 "tags": [
  "conduktor-console",
  "JVM",
  "Pod",
  "Indexer"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "${VAR_NAMESPACE}" },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", job=\"console\"},service)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\", job=\"console\"},pod)"
    }
   },
   {
    "name": "memarea",
    "label": "JVM mem area",
    "query": {
     "query": "label_values(jvm_memory_bytes_used{namespace=\"$namespace\", pod=~\"$pod\"},area)"
    }
   },
   {
    "name": "bufferpool",
    "label": "JVM Buffer pool",
    "query": {
     "query": "label_values(jvm_buffer_pool_used_bytes{namespace=\"$namespace\", pod=~\"$pod\"},pool)"
    }
   },
   {
    "name": "meta_mempool",
    "label": "JVM meta mem pool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{namespace=\"$namespace\", pod=~\"$pod\"},pool)"
    }
   },
   {
    "name": "gc_mempool",
    "label": "JVM GC mem pool",
    "query": {
     "query": "label_values(jvm_memory_pool_bytes_max{namespace=\"$namespace\", pod=~\"$pod\"},pool)"
    }
   },
   {
    "name": "cluster",
    "label": "Kafka Cluster",
    "query": {
     "query": "label_values(console_indexer_kafka_cluster_duration_sum{pod=~\"$pod\"},technical_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\", service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{namespace=\"$namespace\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Kafka clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_cluster_succeeded_count {namespace=\"$namespace\", service=~\"$service\"} + console_indexer_kafka_cluster_failed_count {namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pod resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",  pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",  pod=~\"$pod\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory area [$memarea]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "repeat": "memarea",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"$memarea\",namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "Upper limit"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"$memarea\",namespace=\"$namespace\",pod=~\"$pod\"} / jvm_memory_bytes_max >= 0",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "Buffer pool [$bufferpool]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "repeat": "bufferpool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_pool_capacity_bytes{namespace=\"$namespace\", pod=~\"$pod\", pool=~\"$bufferpool\"}",
     "legendFormat": "Capacity"
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$bufferpool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_buffer_pool_used_buffers{namespace=\"$namespace\", pod=~\"$pod\", pool=~\"$bufferpool\"}",
     "legendFormat": "Used buffer"
    }
   ]
  },
  {
   "title": "Memory pool [$meta_mempool]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "repeat": "meta_mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$meta_mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$meta_mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$meta_mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Memory pool [$gc_mempool]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "repeat": "gc_mempool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$gc_mempool\"}",
     "legendFormat": "Max "
    },
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$gc_mempool\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_pool_bytes_committed{namespace=\"$namespace\",pod=~\"$pod\",pool=~\"$gc_mempool\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  { "title": "JVM misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Threads used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "JVM current threads"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "JVM daemon threads"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "JVM deadlocked threads"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded{namespace=\"$namespace\",pod=~\"$pod\"}",
     "legendFormat": "loaded "
    }
   ]
  },
  { "title": "Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Indexed clusters",
   "type": "stat",
   "description": "Status of Kafka clusters indexing tasks",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_cluster_succeeded_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_cluster_skipped_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Skipped"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_cluster_failed_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_cluster_timeout_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Indexed Schema registry servers",
   "type": "stat",
   "description": "Status of Schema registry servers indexing tasks",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(pod, instance) (console_indexer_schema_registry_cluster_succeeded_count{namespace=\"$namespace\",service=~\"$service\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_schema_registry_cluster_skipped_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Skipped"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_schema_registry_cluster_failed_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_schema_registry_cluster_timeout_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Indexed Kafka Connect servers",
   "type": "stat",
   "description": "Status of Kafka Connect servers indexing tasks",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_connect_cluster_succeeded_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_connect_cluster_skipped_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Skipped"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_connect_cluster_failed_count{namespace=\"$namespace\", service=~\"$service\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "avg without(pod, instance) (console_indexer_kafka_connect_cluster_timeout_count{namespace=\"$namespace\", pod=~\"$pod\"})",
     "legendFormat": "Timeout"
    }
   ]
  },
  {
   "title": "Indexing tasks latency",
   "type": "timeseries",
   "description": "Latency of indexing tasks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(console_indexer_kafka_total_duration_sum{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(console_indexer_kafka_total_duration_count{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Kafka Metadata"
    },
    {
     "expr": "rate(console_indexer_schema_registry_total_duration_sum{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(console_indexer_schema_registry_total_duration_count{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Schema Registry"
    },
    {
     "expr": "rate(console_indexer_kafka_connect_total_duration_sum{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(console_indexer_kafka_connect_total_duration_count{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "Kafka connect"
    }
   ]
  },
  {
   "title": "Cluster operations latencies [$cluster]",
   "type": "timeseries",
   "description": "Latency of queries used to index the clusters",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(console_indexer_kafka_cluster_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_cluster_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Indexing"
    },
    {
     "expr": "rate(console_indexer_kafka_init_cluster_connection_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_init_cluster_connection_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Connection"
    },
    {
     "expr": "rate(console_indexer_kafka_list_topics_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_list_topics_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "List topics"
    },
    {
     "expr": "rate(console_indexer_kafka_describe_topics_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_describe_topics_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Describe topics"
    },
    {
     "expr": "rate(console_indexer_kafka_get_topics_configs_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_get_topics_configs_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Get Topic config"
    },
    {
     "expr": "rate(console_indexer_kafka_get_topics_partitions_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_get_topics_partitions_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Get topics partitions"
    },
    {
     "expr": "rate(console_indexer_kafka_get_consumers_groups_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_get_consumers_groups_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Get consumer groups"
    },
    {
     "expr": "rate(console_indexer_kafka_get_deployed_connectors_duration_sum{namespace=\"$namespace\", pod=~\"$pod\", technical_id=\"$cluster\"}[$__rate_interval]) / rate(console_indexer_kafka_get_deployed_connectors_duration_count{namespace=\"$namespace\", pod=~\"$pod\",technical_id=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Get deployed connectors"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Response latency by requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 19, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(console_api_request_duration_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval]) / rate(console_api_request_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "[{{method}}] {{path}}"
    }
   ]
  },
  {
   "title": "Global latency request response",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(console_api_request_duration_seconds_sum{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) / sum(rate(console_api_request_duration_seconds_count{namespace=\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) > 0",
     "legendFormat": "[avg]"
    },
    {
     "expr": "histogram_quantile(0.3, sum(rate(console_api_request_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\"}[$__range])) by (le)) > 0",
     "legendFormat": "[30p]"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(console_api_request_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\"}[$__range])) by (le)) > 0",
     "legendFormat": "[med]"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(console_api_request_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\"}[$__range])) by (le)) > 0",
     "legendFormat": "[95p]"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(console_api_request_duration_seconds_bucket{namespace=\"$namespace\", pod=~\"$pod\"}[$__range])) by (le)) > 0",
     "legendFormat": "[99p]"
    }
   ]
  }
 ]
}